# Generated by Django 4.2.26 on 2025-11-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0002_receiptlineitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='quantity',
            new_name='quantity_change',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('DELIVERY', 'Delivery Order'), ('TRANSFER', 'Internal Transfer'), ('ADJUSTMENT', 'Stock Adjustment')], default='RECEIPT', max_length=20),
        ),
    ]
