# Generated by Django 4.2.26 on 2025-11-22 05:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0003_rename_quantity_stocktransaction_quantity_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING', 'Waiting'), ('READY', 'Ready'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='internaltransfer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING', 'Waiting'), ('READY', 'Ready'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING', 'Waiting'), ('READY', 'Ready'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING', 'Waiting'), ('READY', 'Ready'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('DELIVERY', 'Delivery Order'), ('TRANSFER', 'Internal Transfer'), ('ADJUSTMENT', 'Stock Adjustment')], db_index=True, default='RECEIPT', max_length=20),
        ),
        migrations.CreateModel(
            name='TransferLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_core.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_core.internaltransfer')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_core.deliveryorder')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_core.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_core.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.DecimalField(decimal_places=4, max_digits=15)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_core.stockadjustment')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_core.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_core.product')),
            ],
        ),
    ]
