# Generated by Django 4.2.26 on 2025-11-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_core', '0005_purchaseorder_vendor_product_lead_time_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='blockchain_hash',
            field=models.CharField(blank=True, help_text='Hash from blockchain for provenance', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='blockchain_hash',
            field=models.CharField(blank=True, help_text='Hash from blockchain for provenance', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='blockchain_hash',
            field=models.CharField(blank=True, help_text='Hash from blockchain for provenance', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='blockchain_hash',
            field=models.CharField(blank=True, help_text='Hash from blockchain for provenance', max_length=256, null=True),
        ),
    ]
